basic_settings:
  site_title: PMB
  favicon_image: /assets/img/slack.png

header_settings:
  logo_image:  assets/img/house-512.png
  mobile_logo_image:  assets/img/house-512.png
    
  # Choose a color for your header [blue, dark, light].
  theme: dark
  # If the page has a featured image, it turns transparent if allow_transparent is set to "yes".
  allow_transparent: "yes"

home_settings:
  # Choose a layout for your home page:
    # landing – an example landing page made using the Argon design system
    # blog – use your blog posts as the home page
  theme: landing

blog_settings:
  # Choose a format for your blog listings:
    # basic – a simple list of posts
    # narrow – a masonary grid of posts
    # grid – a full-width square grid of posts
  theme: narrow
  # Should we display a narrow grid of other posts at the bottom of each blog post?
  read_more: "no"

# Setup your navigation below – how to use the icons: 
  # 1. See all the icons available here https://demos.creative-tim.com/argon-design-system-pro/docs/1.0/foundation/icons.html
  # 2. Get the name of the icon e.g basket, then prefix with ni to make ni-basket. 
  # 3. Add a color of the icon - text-primary, text-success, text-info, text-danger, text-warning and text-default all work! 
menu_settings:
  menu_items:
    #- title: 'Professional'
     #        icon: ni-spaceship text-success    
     #- title: 'Features'
      #url: '/features'     
 
    - title: 'Professional'
      submenu_items:
      - title: My Portfolio
        url: /blog-list-example
        icon: ni-books text-primary
      - title: Resume
        url: /features
        icon: ni-align-center text-success
             #- title: Wide Grid Example
       # url: /blog-grid-example
        #icon: ni-image text-info
      #- title: List Example
       # url: /blog-list-example
        #icon: ni-bullet-list-67 text-default  
    - social_settings:
       linkedin_url: 'https://www.linkedin.com/in/patriciamariebarrier/'
    - title: 'About Me'
      url: '/about'
    - title: 'Contact'
      url: '/contact'

footer_settings:
  footer_tagline: Statistician and Data Scientist
  Data Science and Statistics [8 years], Machine Learning [4 years], Python [<1 year], R [5 years], SQL [4 years], JQL [1 year, Jira SME], C++ [2 years]
  
MA Mathematics, Appalachian State University, 2006
MS Data Science and Business Analytics, University of North Carolina Charlotte, Pending 2024
Graduate Certificate, Data Science and Business Analytics, University of North Carolina Charlotte, 2021
BS Mathematics with minor in Computer Science, Appalachian State University, 2004

contact_settings:
  form_action: 'https://formspree.io/f/mjvpoong'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

  analytics_code: 
  header_js: 
  footer_js: 
